name: triggers example
on:
 push:
  branches:
  - "test/*"
 workflow_dispatch:
 pull_request:
  paths:
  - "sixer/chapter-1/*"
 schedule:
 - cron: "0 0 * * *"
jobs:
 job1:
  runs-on: ubuntu-24.04
  steps:
  - run: echo "Hello world!"
