name: test wf
on: workflow_dispatch
jobs:
 printenv:
  runs-on: ubuntu-24.04
  environment: dev
  env:
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  steps:
   - name: show env
     run: |
      echo "AWS_ACCESS_KEY is ${AWS_ACCESS_KEY:0:4} and  ${AWS_ACCESS_KEY:4:11}"
      echo "AWS_SECRET_KEY is ${AWS_SECRET_KEY:0:4} and ${AWS_ACCESS_KEY:4:17}"
   
